# Generated by Django 2.0.6 on 2018-07-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0006_auto_20180630_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parent_task_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='task_group',
            field=models.CharField(default='TASK', max_length=5),
        ),
        migrations.AddField(
            model_name='task',
            name='task_group_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
